In [1]:
# Import required modules 
import cv2 
import numpy as np 
import os 
import glob 


# Define the dimensions of checkerboard 
CHECKERBOARD = (6,9) 


# stop the iteration when specified 
# accuracy, epsilon, is reached or 
# specified number of iterations are completed. 
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001) 


# Vector for 3D points 
threedpoints = [] 

# Vector for 2D points 
twodpoints = [] 


# 3D points real world coordinates 
objectp3d = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32) 
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2) 
prev_img_shape = None


# Extracting path of individual image stored 
# in a given directory. Since no path is 
# specified, it will take current directory 
# jpg files alone 
images = glob.glob(r'C:\Users\harip25\3D Objects\final1\*.jpg') 

for filename in images: 
	image = cv2.imread(filename) 
	grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 

	# Find the chess board corners 
	# If desired number of corners are 
	# found in the image then ret = true 
	ret, corners = cv2.findChessboardCorners( 
					grayColor, CHECKERBOARD, 
					cv2.CALIB_CB_ADAPTIVE_THRESH 
					+ cv2.CALIB_CB_FAST_CHECK +
					cv2.CALIB_CB_NORMALIZE_IMAGE) 

	# If desired number of corners can be detected then, 
	# refine the pixel coordinates and display 
	# them on the images of checker board 
	if ret == True: 
		threedpoints.append(objectp3d) 

		# Refining pixel coordinates 
		# for given 2d points. 
		corners2 = cv2.cornerSubPix( grayColor, corners, (11, 11), (-1, -1), criteria) 

		twodpoints.append(corners2) 

		# Draw and display the corners 
		image = cv2.drawChessboardCorners(image, CHECKERBOARD, corners2, ret) 

	cv2.imshow('img', image) 
	cv2.waitKey(0) 

cv2.destroyAllWindows() 
h, w = image.shape[:2] 


# Perform camera calibration by 
# passing the value of above found out 3D points (threedpoints) 
# and its corresponding pixel coordinates of the 
# detected corners (twodpoints) 
ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera( 
	threedpoints, twodpoints, grayColor.shape[::-1], None, None) 



# Displayig required output 
print(" Camera matrix:") 
print(matrix) 

print("\n Distortion coefficient:") 
print(distortion) 

print("\n Rotation Vectors:") 
print(r_vecs) 

print("\n Translation Vectors:") 
print(t_vecs) 


 Camera matrix:
[[3.03899263e+03 0.00000000e+00 1.49804134e+03]
 [0.00000000e+00 3.03552688e+03 1.99105841e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

 Distortion coefficient:
[[-1.65357248e-02  1.95393621e-01  1.73253607e-04  1.32382777e-03
  -1.85870112e-01]]

 Rotation Vectors:
[array([[ 0.49624183],
       [-0.51084449],
       [-1.47812716]]), array([[-0.51126798],
       [ 0.53029699],
       [-1.48448206]]), array([[ 0.6058342 ],
       [-0.51487298],
       [-1.51745686]]), array([[ 0.03684077],
       [ 0.03863652],
       [-1.5712386 ]]), array([[-0.39250679],
       [-0.45482728],
       [-1.46301911]]), array([[ 0.39264161],
       [ 0.47244686],
       [-1.46235663]]), array([[-0.74736067],
       [ 0.4868226 ],
       [-1.52194023]]), array([[-0.56884139],
       [ 0.71185887],
       [-1.14064151]]), array([[ 0.43432956],
       [-0.91384932],
       [-1.24573341]]), array([[ 0.76920285],
       [-0.3752281 ],
       [-1.52821089]]), array([[-0.53038091],
    

#new

In [6]:
import lensfunpy

ModuleNotFoundError: No module named 'lensfunpy'

In [2]:
img = cv2.imread(r'F:\New folder\Due Date (2010)\New folder (5)\Downloads\IMG_20210430_173243.jpg')
h,  w = img.shape[:2]
newcameramtx, roi=cv2.getOptimalNewCameraMatrix(matrix,distortion,(w,h),1,(w,h))

mapx,mapy = cv2.initUndistortRectifyMap(matrix,distortion,None,newcameramtx,(w,h),5)
dst = cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)

# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite(r'C:\Users\harip25\Desktop\try\calibresult.jpg',dst)

True

In [ ]:
ex=np.column_stack((r_vecs[3],t_vecs[3]))
res=np.dot(matrix,ex)
print(res)

In [ ]:
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(matrix, distortion, (w,h), 1, (w,h))

# undistort

img = cv2.imread(r'C:\Users\harip25\Desktop\try\hmm.jpg')
dst = cv2.undistort(img, matrix, distortion, None, newcameramtx)

path = r'C:\Users\harip25\Desktop'
cv2.imwrite(os.path.join(path,'fimg1.jpg'),dst)
#cv2.imwrite('calibresult.png', dst)


In [ ]:
rotation_mat = np.zeros(shape=(3, 3))
R = cv2.Rodrigues(r_vecs[3], rotation_mat)[0]
m = np.column_stack((np.matmul(matrix,R), t_vecs[3]))
print(m)

In [ ]:
m=[[-7.43750617e+01 , 3.03725020e+03, 0,-3.36528377e+00],
 [-3.12764789e+03 ,-4.57096726e+00,  0,1.71643074e+00],
 [-4.80271628e-02 , -1.16120922e-03,  0, 1.52733433e+01]]

In [ ]:
v0=3726
v1=3510
v2=3215
v3=2779
u0=2523
u1=2523
u2=2523
u3=2523
hi=30

In [ ]:
A=  [[u0*m[2][0]-m[0][0],u0*m[2][1]-m[0][1],u0*m[2][2]-m[0][2]],
        [v0*m[2][0]-m[1][0],v0*m[2][1]-m[1][1],v0*m[2][2]-m[1][2]],
        [u1*m[2][0]-m[0][0],u1*m[2][1]-m[0][1],u1*m[2][2]-m[0][2]],
        [v1*m[2][0]-m[1][0],v1*m[2][1]-m[1][1],v1*m[2][2]-m[1][2]],
        [u2*m[2][0]-m[0][0],u2*m[2][1]-m[0][1],u2*m[2][2]-m[0][2]],
        [v2*m[2][0]-m[1][0],v2*m[2][1]-m[1][1],v2*m[2][2]-m[1][2]]]

In [ ]:
print(A)

In [ ]:
B= [[m[0][3]-u0*m[2][3]],
    [m[1][3]-v0*m[2][3]],
    [m[0][3]-u1*m[2][3]-(u1*m[2][2]-m[0][2])*hi],
    [m[1][3]-v1*m[2][3]-(v1*m[2][2]-m[1][2])*hi],
    [m[0][3]-u2*m[2][3]-2.618*(u2*m[2][2]-m[0][2])*hi],
    [m[1][3]-v2*m[2][3]-2.618*(v2*m[2][2]-m[1][2])*hi]]

In [ ]:
print(B)

In [ ]:
a=np.transpose(A)

In [ ]:
b=np.matmul(a,A)
print(b)

In [ ]:
c=np.linalg.inv(b)
d=np.matmul(c,a)
e=np.matmul(d,B)

In [ ]:
print(e)

In [ ]:
H=(m[1][3]-v3*m[2][3]-(v3*m[2][0]-m[1][0])*e[0]-(v3*m[2][1]-m[1][1])*e[1])/(v3*m[2][2]-m[1][2])

In [ ]:
print(H)

In [ ]:
print((m[1][3]-v3*m[2][3]-(v3*m[2][0]-m[1][0])*e[0]-(v3*m[2][1]-m[1][1])*e[1]),(v3*m[2][2]-m[1][2]))

In [ ]:
z=[[2523],
   [3726],
   [1]]
m1=[[-7.43750617e+01 , 3.03725020e+03,-3.36528377e+00],
 [-3.12764789e+03 ,-4.57096726e+00, 1.71643074e+00],
 [-4.80271628e-02 , -1.16120922e-03, 1.52733433e+01]]
c1=np.linalg.inv(m1)
e1=np.matmul(c1,z)
print (c1)
print(np.matmul(c1,z))

In [ ]:
print((m[1][3]-v3*m[2][3]-(v3*m[2][0]-m[1][0])*e1[0]-(v3*m[2][1]-m[1][1])*e1[1]),(v3*m[2][2]-m[1][2]))